language:
  explicit: ["go"]           # Override auto-detect: ["go", "python"]
  go:   
    coverage_threshold: 50

# Required files to check
files:
  required:
    - README.md
    - LICENSE
    - CONTRIBUTING.md

# Disable specific checks
checks:
  disabled:
    - deps  # Skip vulnerability check

# Execution options
execution:
  parallel: true  # Run checks in parallel (default: true). Set to false for CI with limited CPU.

# Custom external checks
external:
  - id: lint
    name: Golangci-lint
    command: golangci-lint
    args: ["run", "./..."]
    severity: warn

  - id: security
    name: Security Scan
    command: gosec
    args: ["./..."]
    severity: fail
  
  - id: security
    name: Trufflehog
    command: trufflehog
    args: ["filesystem", "--no-update", "--fail", "--log-level=-1", "."]
    severity: warn
    
  - id: secrets
    name: Secret Detection
    command: gitleaks
    args: ["detect", "--no-git", "--redact", "-v", "."]
    severity: fail

  - id: go:errcheck
    name: Error Check
    command: errcheck
    args: ["-ignoretests", "./..."]
    severity: warn

  - id: go:staticcheck
    name: Static Analysis
    command: staticcheck
    args: ["./..."]
    severity: warn

  - id: python:bandit
    name: Bandit Security
    command: bandit
    args: ["-r", ".", "-f", "json", "-q"]
    severity: warn

  - id: sast
    name: Semgrep SAST
    command: semgrep
    args: ["scan", "--config", "auto", "--error", "."]
    severity: warn  