language:
  explicit: ["go"]           # Override auto-detect: ["go", "python"]
  go:   
    coverage_threshold: 60

# Required files to check
files:
  required:
    - README.md
    - LICENSE
    - CONTRIBUTING.md

# Disable specific checks
checks:
  disabled:
    - go:logging  # Skip logging check
    - common:health  # Skip health check
    - common:k8s  # Skip k8s check
    - common:api_docs  # Skip api docs check
    - common:integration  # Skip integration check
    - common:metrics  # Skip metrics check
    - common:errors  # Skip errors check
    - common:license  # Skip license check
    - common:tracing  # Skip tracing check
    - common:migrations  # Skip migrations check
    - common:e2e  # Skip e2e tests check
    - common:config_validation  # Skip config validation check
    - common:retry  # Skip retry check
    - common:dockerfile  # Skip dockerfile check
    - devops:*  # Skip ansible check
    - security:shell_injection
    
# Execution options
execution:
  parallel: true  # Run checks in parallel (default: true). Set to false for CI with limited CPU.

# Custom external checks
external:
  - id: lint
    name: Golangci-lint
    command: golangci-lint
    args: ["run", "./..."]
    severity: warn

# This check is an order of magnitude slower than the others
  # Optional source_dir: run the command in a subdir (e.g. when Go code lives in backend/)
  - id: security
    name: Security Scan
    command: gosec
    args: ["./..."]
    severity: fail
    # source_dir: backend   # uncomment if Go code is in backend/

  # - id: secrets
  #   name: Secret Detection
  #   command: gitleaks
  #   args: ["detect", "--no-git", "--redact", "-v", "--config", ".gitleaks.toml", "."]
  #   severity: fail

  - id: go:errcheck
    name: Error Check
    command: errcheck
    args: ["-ignoretests", "./..."]
    severity: warn

  - id: go:staticcheck
    name: Static Analysis
    command: staticcheck
    args: ["./..."]
    severity: warn
  
  # - id: go:golicense
  #   name: Go License
  #   command: go-licenses
  #   args: ["check", "./...", "--ignore", "github.com/ipedrazas/a2", "./..."]
  #   severity: warn
