version: '3'

vars:
  BINARY: a2
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  GITSHA:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILDDATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ"
  REGISTRY: docker.io
  DOCKER_USER: ipedrazas

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
  
  dependencies:
    desc: Install dependencies
    cmds:
      - go mod tidy
      - go mod download
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - go install honnef.co/go/tools/cmd/staticcheck@2025.1.1
      - go install github.com/kisielk/errcheck@latest
      - go install github.com/google/go-licenses/v2@latest
      

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" -o dist/{{.BINARY}} .
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - '{{.BINARY}}'

  run:
    desc: Run a2 check on current directory
    deps: [build]
    cmds:
      - ./{{.BINARY}} check {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:unit:
    desc: Run unit tests only (excludes integration)
    cmds:
      - go test -v -short ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report available at coverage.html"

  test:coverage:bypackage:
    desc: Show coverage by package
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report available at coverage.html"

  test:validate:
    desc: Validate all tests pass and show summary
    cmds:
      - go test -v ./... 2>&1 | tee test-output.log
      - echo "Test summary:"
      - grep -E "^(PASS|FAIL|ok|FAIL)" test-output.log | tail -20 || true
      - rm -f test-output.log

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - gofmt -l . | grep -q . && echo "Files need formatting" && exit 1 || true

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f dist/{{.BINARY}}
      - rm -f coverage.out coverage.html

  install:
    desc: Install a2 to GOPATH/bin
    deps: [build]
    cmds:
      - go install -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" .

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --build-arg GITSHA={{.GITSHA}} --build-arg BUILDDATE={{.BUILDDATE}} -t {{.BINARY}}:{{.VERSION}} -t {{.REGISTRY}}/{{.DOCKER_USER}}/{{.BINARY}}:latest .

  docker:run:
    desc: Run a2 in Docker
    cmds:
      - docker run -v $(pwd):/workspace {{.REGISTRY}}/{{.DOCKER_USER}}/{{.BINARY}}:latest check {{.CLI_ARGS}}

  release:
    desc: Build release binaries for all platforms
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" -o dist/{{.BINARY}}-linux-amd64 .
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" -o dist/{{.BINARY}}-linux-arm64 .
      - GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" -o dist/{{.BINARY}}-darwin-amd64 .
      - GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" -o dist/{{.BINARY}}-darwin-arm64 .
      - GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X github.com/ipedrazas/a2/pkg/version.Version={{.VERSION}} -X github.com/ipedrazas/a2/pkg/version.GitSHA={{.GITSHA}} -X github.com/ipedrazas/a2/pkg/version.BuildDate={{.BUILDDATE}}" -o dist/{{.BINARY}}-windows-amd64.exe .
    generates:
      - dist/*

  ci:
    desc: Run all CI checks
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build
      - ./dist/{{.BINARY}} check

  all:
    desc: Build, test, and run checks
    cmds:
      - task: tidy
      - task: fmt
      - task: build
      - task: test
      - task: run

  # Server tasks
  server:ui:build:
    desc: Build the React UI for production
    dir: ui
    cmds:
      - npm ci
      - npm run build
    sources:
      - ui/src/**/*
      - ui/package.json
      - ui/vite.config.ts
      - ui/tailwind.config.js
      - ui/tsconfig.json
    generates:
      - ui/dist/**

  server:build:
    desc: Build Docker image with UI (server mode)
    deps: [server:ui:build]
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --build-arg GITSHA={{.GITSHA}} --build-arg BUILDDATE={{.BUILDDATE}} -t {{.BINARY}}-server:{{.VERSION}} -t {{.BINARY}}-server:latest .

  server:run:
    desc: Run a2 server in Docker
    cmds:
      - docker run -p 8080:8080 -v a2-cache:/workspace/a2-cache {{.BINARY}}-server:latest server --port 8080

  server:dev:
    desc: Run a2 server locally (requires Go)
    cmds:
      - go run . server --port 8080 --workspace-dir ./a2-cache {{.CLI_ARGS}}

  server:dev:ui:
    desc: Run React UI dev server (for development)
    dir: ui
    cmds:
      - npm run dev
