package config

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"
)

type GeneratorTestSuite struct {
	suite.Suite
}

func TestGeneratorSuite(t *testing.T) {
	suite.Run(t, new(GeneratorTestSuite))
}

func (s *GeneratorTestSuite) TestGenerate_DefaultOptions() {
	opts := GeneratorOptions{}
	cfg := Generate(opts)

	assert.NotNil(s.T(), cfg)
	assert.Equal(s.T(), 80.0, cfg.Coverage.Threshold)
	assert.Equal(s.T(), []string{"README.md", "LICENSE"}, cfg.Files.Required)
	assert.Empty(s.T(), cfg.Language.Explicit)
}

func (s *GeneratorTestSuite) TestGenerate_WithLanguages() {
	opts := GeneratorOptions{
		Languages: []string{"go", "python"},
	}
	cfg := Generate(opts)

	assert.Equal(s.T(), []string{"go", "python"}, cfg.Language.Explicit)
}

func (s *GeneratorTestSuite) TestGenerate_WithFiles() {
	opts := GeneratorOptions{
		Files: []string{"README.md", "LICENSE", "CHANGELOG.md"},
	}
	cfg := Generate(opts)

	assert.Equal(s.T(), []string{"README.md", "LICENSE", "CHANGELOG.md"}, cfg.Files.Required)
}

func (s *GeneratorTestSuite) TestGenerate_WithCoverage() {
	opts := GeneratorOptions{
		Coverage: 90.0,
	}
	cfg := Generate(opts)

	assert.Equal(s.T(), 90.0, cfg.Coverage.Threshold)
}

func (s *GeneratorTestSuite) TestToYAML_DefaultOptions() {
	opts := GeneratorOptions{}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "# A2 Configuration")
	assert.Contains(s.T(), yaml, "# Generated by: a2 add")
	assert.Contains(s.T(), yaml, "# Using all default settings")
}

func (s *GeneratorTestSuite) TestToYAML_WithProfile() {
	opts := GeneratorOptions{
		Profile: "cli",
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "# Profile: cli")
	assert.Contains(s.T(), yaml, "--profile cli")
}

func (s *GeneratorTestSuite) TestToYAML_WithTarget() {
	opts := GeneratorOptions{
		Target: "poc",
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "# Target: poc")
	assert.Contains(s.T(), yaml, "--target poc")
}

func (s *GeneratorTestSuite) TestToYAML_WithLanguages() {
	opts := GeneratorOptions{
		Languages: []string{"go", "python"},
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "language:")
	assert.Contains(s.T(), yaml, "explicit:")
	assert.Contains(s.T(), yaml, "go")
	assert.Contains(s.T(), yaml, "python")
}

func (s *GeneratorTestSuite) TestToYAML_WithCustomCoverage() {
	opts := GeneratorOptions{
		Coverage: 90.0,
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "coverage:")
	assert.Contains(s.T(), yaml, "threshold: 90")
}

func (s *GeneratorTestSuite) TestToYAML_WithCustomFiles() {
	opts := GeneratorOptions{
		Files: []string{"README.md", "LICENSE", "CHANGELOG.md"},
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "files:")
	assert.Contains(s.T(), yaml, "required:")
	assert.Contains(s.T(), yaml, "CHANGELOG.md")
}

func (s *GeneratorTestSuite) TestToYAML_FullOptions() {
	opts := GeneratorOptions{
		Profile:   "api",
		Target:    "production",
		Languages: []string{"go"},
		Files:     []string{"README.md"},
		Coverage:  95.0,
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(s.T(), err)

	yaml := string(yamlData)
	assert.Contains(s.T(), yaml, "# Profile: api")
	assert.Contains(s.T(), yaml, "# Target: production")
	assert.Contains(s.T(), yaml, "explicit:")
	assert.Contains(s.T(), yaml, "threshold: 95")
}

func (s *GeneratorTestSuite) TestStringSliceEqual() {
	assert.True(s.T(), stringSliceEqual([]string{"a", "b"}, []string{"a", "b"}))
	assert.False(s.T(), stringSliceEqual([]string{"a", "b"}, []string{"a", "c"}))
	assert.False(s.T(), stringSliceEqual([]string{"a", "b"}, []string{"a"}))
	assert.False(s.T(), stringSliceEqual([]string{"a"}, []string{"a", "b"}))
	assert.True(s.T(), stringSliceEqual([]string{}, []string{}))
	assert.True(s.T(), stringSliceEqual(nil, nil))
}

func TestToYAML_NoExcessiveNewlines(t *testing.T) {
	opts := GeneratorOptions{
		Languages: []string{"go"},
	}
	cfg := Generate(opts)

	yamlData, err := ToYAML(cfg, opts)
	assert.NoError(t, err)

	// Should not have triple newlines
	assert.False(t, strings.Contains(string(yamlData), "\n\n\n"))
}
