package config

import (
	"bytes"
	"fmt"
	"strings"
)

// GeneratorOptions contains the options for generating a config file.
type GeneratorOptions struct {
	Profile   string   // Application profile (cli, api, library, desktop)
	Target    string   // Maturity target (poc, production)
	Languages []string // Explicit languages to check
	Files     []string // Required files
	Coverage  float64  // Coverage threshold (0 means use default)
}

// Generate creates a Config from the given options.
func Generate(opts GeneratorOptions) *Config {
	cfg := DefaultConfig()

	// Set explicit languages if provided
	if len(opts.Languages) > 0 {
		cfg.Language.Explicit = opts.Languages
	}

	// Set required files if provided
	if len(opts.Files) > 0 {
		cfg.Files.Required = opts.Files
	}

	// Set coverage threshold if provided (non-zero)
	if opts.Coverage > 0 {
		cfg.Coverage.Threshold = opts.Coverage
	}

	return cfg
}

// ToYAML converts a Config to an annotated YAML document.
// Unlike a minimal dump, it emits a small but *active* baseline with inline
// comments explaining each block, so a freshly generated .a2.yaml is a working
// example users can read and edit rather than a wall of commented-out hints.
func ToYAML(cfg *Config, opts GeneratorOptions) ([]byte, error) {
	var buf bytes.Buffer

	// Header with profile/target context and the handful of commands users need.
	buf.WriteString("# A2 Configuration\n")
	buf.WriteString("# Generated by: a2 init\n")
	if opts.Profile != "" {
		fmt.Fprintf(&buf, "# Profile: %s\n", opts.Profile)
	}
	if opts.Target != "" {
		fmt.Fprintf(&buf, "# Target: %s\n", opts.Target)
	}
	buf.WriteString("#\n")
	buf.WriteString("# Run checks with: a2 check")
	if opts.Profile != "" {
		fmt.Fprintf(&buf, " --profile %s", opts.Profile)
	}
	if opts.Target != "" {
		fmt.Fprintf(&buf, " --target %s", opts.Target)
	}
	buf.WriteString("\n")
	buf.WriteString("# List all checks: a2 list checks   ·   Explain one: a2 explain <id>\n\n")

	// Languages: active when explicitly chosen, otherwise a commented hint so
	// auto-detection stays on by default.
	if len(cfg.Language.Explicit) > 0 {
		buf.WriteString("# Languages to check (overrides auto-detection).\n")
		buf.WriteString("language:\n")
		fmt.Fprintf(&buf, "  explicit: [%s]\n\n", strings.Join(cfg.Language.Explicit, ", "))
	} else {
		buf.WriteString("# Languages to check. Commented out = auto-detect from the repo.\n")
		buf.WriteString("# language:\n")
		buf.WriteString("#   explicit: [go]\n\n")
	}

	// Files: active. Default to README + LICENSE when nothing was chosen.
	required := cfg.Files.Required
	if len(required) == 0 {
		required = []string{"README.md", "LICENSE"}
	}
	buf.WriteString("# Files that must exist in the repository root.\n")
	buf.WriteString("files:\n")
	buf.WriteString("  required:\n")
	for _, f := range required {
		fmt.Fprintf(&buf, "    - %s\n", f)
	}
	buf.WriteString("\n")

	// Coverage: active. Default threshold is 80.
	threshold := cfg.Coverage.Threshold
	if threshold == 0 {
		threshold = 80
	}
	buf.WriteString("# Minimum test-coverage percentage enforced by the coverage checks.\n")
	buf.WriteString("coverage:\n")
	fmt.Fprintf(&buf, "  threshold: %s\n\n", formatThreshold(threshold))

	// Execution: active, with the concurrency knob shown but commented.
	buf.WriteString("# How checks are executed.\n")
	buf.WriteString("execution:\n")
	buf.WriteString("  parallel: true      # run checks concurrently\n")
	buf.WriteString("  # concurrency: 0    # max checks at once (0 = number of CPUs)\n\n")

	// Checks: active empty disable list with commented examples.
	buf.WriteString("# Disable individual checks by ID (see 'a2 list checks').\n")
	buf.WriteString("checks:\n")
	buf.WriteString("  disabled: []\n")
	buf.WriteString("    # - go:coverage\n")
	buf.WriteString("    # - common:health\n\n")

	// External checks: commented example showing every field, including speed.
	buf.WriteString("# Custom checks that run any shell command.\n")
	buf.WriteString("# external:\n")
	buf.WriteString("#   - id: lint\n")
	buf.WriteString("#     name: golangci-lint\n")
	buf.WriteString("#     command: golangci-lint\n")
	buf.WriteString("#     args: [\"run\", \"./...\"]\n")
	buf.WriteString("#     severity: warn    # warn | fail\n")
	buf.WriteString("#     speed: slow       # slow checks are skipped by 'a2 check --quick'\n")

	return buf.Bytes(), nil
}

// formatThreshold prints a coverage threshold without a trailing ".0".
func formatThreshold(t float64) string {
	if t == float64(int64(t)) {
		return fmt.Sprintf("%d", int64(t))
	}
	return fmt.Sprintf("%g", t)
}

// stringSliceEqual checks if two string slices are equal.
func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
